#!/bin/bash
# Copyright (C) 2014 Julien Bonjean <julien@bonjean.info>
# Copyright (C) 2014 Alexander Keller <github@nycroth.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

#------------------------------------------------------------------------

seconds="$(< /proc/uptime)"
seconds="${seconds/.*}"

days="$((seconds / 60 / 60 / 24))"
hours="$((seconds / 60 / 60 % 24))"
mins="$((seconds / 60 % 60)) min"


if [[ "$days" != "0" ]];then
        if [[ "$days" = "1" ]] && [[ "$hours" = "1" ]];then
                uptime="$days day, $hours hr, $mins"
                echo "$uptime"
        elif [[ "$days" = "1" ]] && [[ "$hours" != "1" ]];then
                uptime="$days day, $hours hrs, $mins"
                echo "$uptime"
        else
                uptime="$days days, $hours hrs, $mins"
                echo "$uptime"
        fi
elif [[ "$hours" = "0" ]];then
        uptime="$mins"
        echo "$uptime"
else
        uptime="$hours hrs, $mins"
        echo "$uptime"
fi
